from vitrine_ai.narratives import (
    CuratorNarrative,
    NarrativeSection,
    batch_narratives,
    generate_curator_narrative,
    narrative_to_markdown,
)
from vitrine_ai.recommender import (
    ExhibitionMatch,
    TransitionSuggestion,
    exhibition_similarity,
    find_similar_exhibitions,
    recommend_pacing_adjustments,
    suggest_transitions,
)
from vitrine_ai.similarity import (
    FeatureVector,
    SimilarityResult,
    composite_similarity,
    cosine_similarity,
    exhibition_feature_vector,
    find_nearest_neighbors,
    jaccard_similarity,
    rank_similar,
)
from vitrine_ai.transitions import (
    PathScore,
    TransitionCell,
    TransitionMatrix,
    build_transition_matrix,
    optimal_reorder_greedy,
    score_path,
    sequential_transitions,
    transition_entropy,
)

__all__ = [
    "CuratorNarrative",
    "ExhibitionMatch",
    "FeatureVector",
    "NarrativeSection",
    "PathScore",
    "SimilarityResult",
    "TransitionCell",
    "TransitionMatrix",
    "TransitionSuggestion",
    "batch_narratives",
    "build_transition_matrix",
    "composite_similarity",
    "cosine_similarity",
    "exhibition_feature_vector",
    "exhibition_similarity",
    "find_nearest_neighbors",
    "find_similar_exhibitions",
    "generate_curator_narrative",
    "jaccard_similarity",
    "narrative_to_markdown",
    "optimal_reorder_greedy",
    "rank_similar",
    "recommend_pacing_adjustments",
    "score_path",
    "sequential_transitions",
    "suggest_transitions",
    "transition_entropy",
]
